default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  pool: 2
  database: trello_hill_chart_dev

test:
  <<: *default
  pool: 1
  database: trello_hill_chart_test

production:
  pool: 5
  host: <%= ENV['DATABASE_URL'] %>
